### ISSUE TITLE
How do I set it up?

### ISSUE THREAD

**Issue by vladns** [Andrwe/privoxy-blocklist#33] opened 2023-05-21 20:40 UTC
The first run of the script reported "No config found in /etc/privoxy-blocklist.conf. Fixed it. What should be there? Examples? I also noticed that only the blocklist "easylistgermany.txt" is loaded, no matter what I configured in the URLS variable. Then I removed the file /etc/privoxy-blocklist.conf, but the error message did not appear as it did the first time. The -c switch gives the message: "./privoxy-blocklist.sh: line 331: TMPNAME: variable bounds not set". What should the scope be?

**Comment by Andrwe** [comment] 2024-01-07 11:41
> "./privoxy-blocklist.sh: line 331: TMPNAME: variable bounds not set"

This error message is now fixed in main-branch and will be release with 0.4.0. Thanks for reporting.


Concerning the configuration, a default configuration will be created upon first run of privoxy-blocklist.sh in `/etc/privoxy-blocklist.conf` for Linux and `/usr/local/etc/privoxy-blocklist.conf` for MacOS.
The creation process is indicated by the message `No config found in ...config-path.... Creating default one and exiting because you might have to adjust it.`.
After that you can change the configuration to for example use a different list.

> I also noticed that only the blocklist "easylistgermany.txt" is loaded, no matter what I configured in the URLS variable.

I cannot reproduce this issue yet, can you please provide your configuration file and the output of a script-run?

**Comment by Andrwe** [comment] 2024-01-10 00:02
> I also noticed that only the blocklist "easylistgermany.txt" is loaded, no matter what I configured in the URLS variable.

I created a unit test based on an [extended URL list](https://github.com/Andrwe/privoxy-blocklist/blob/main/tests/configs/url_extended_config.conf) which showed that lists without the `[Adblock …]`-header were not processed. It was implemented that way back then to ensure that the given file can be handled by the script. An information was printed and the processing skipped.

Due to the increased amount of blocklists that don't specify the header anymore I changed the implementation.
Now (since #44) a yellow hint is printed and the list is processed.

As far as I understand you, all issues you found are now fixed in main-branch and will be released after further testing with version 0.4.0, thus closing this issue.

**Closed by Andrwe** 2024-01-10 00:02 UTC
